import { Category, Product } from './types'

export const categories: Category[] = [
  {
    id: 'veterinary-items',
    name: 'VETERINARY ITEMS',
    subcategories: [
      { id: 'hoof-knife', name: 'Hoof Knife' },
      { id: 'hoof-scraper', name: 'Hoof Scraper' },
      { id: 'hoof-rasp', name: 'Hoof Rasp' },
      { id: 'anti-kick-bar', name: 'Anti Kick Bar' },
      { id: 'balling-guns', name: 'Balling Guns' },
      { id: 'bits', name: 'Bits' },
      { id: 'bull-holders', name: 'Bull Holders' },
      { id: 'bull-rings', name: 'Bull Rings' },
      { id: 'castration', name: 'Castration' },
      { id: 'cattle-weaner', name: 'Cattle Weaner' },
      { id: 'cattle-hobble', name: 'Cattle Hobble' },
      { id: 'dehorner', name: 'Dehorner' },
      { id: 'elastrator', name: 'Elastrator' },
      { id: 'forceps-needle-holders', name: 'Forceps & Needle Holders' },
      { id: 'hog-holders', name: 'Hog Holders' },
      { id: 'hoof-clamps', name: 'Hoof Clamps' },
      { id: 'hoof-testing-pliers', name: 'Hoof Testing Pliers' },
      { id: 'leather-products', name: 'Leather Products' },
      { id: 'meat-hooks-chains', name: 'Meat Hook, Chains, Spare Valve' },
      { id: 'milking-tube', name: 'Milking Tube' },
      { id: 'mouth-gags', name: 'Mouth Gags' },
      { id: 'muzzle', name: 'Muzzle' },
      { id: 'pliers', name: 'Pliers' },
      { id: 'scissors', name: 'Scissors' },
      { id: 'sheep-shears', name: 'Sheep Shears' },
      { id: 'shepherds-sticks', name: 'Shepherds Sticks' },
      { id: 'stirrups', name: 'Stirrups' },
      { id: 'tag-applicators', name: 'Tag Applicators' },
      { id: 'trocars', name: 'Trocars' },
      { id: 'whisks', name: 'Whisks' },
    ],
  },
  {
    id: 'surgical-items',
    name: 'SURGICAL ITEMS',
    subcategories: [
      { id: 'surgical-scissors', name: 'Surgical Scissors' },
      { id: 'surgical-forceps', name: 'Surgical Forceps' },
      { id: 'needle-holders', name: 'Needle Holders' },
      { id: 'retractors', name: 'Retractors' },
      { id: 'scalpels', name: 'Scalpels' },
    ],
  },
  {
    id: 'dental-items',
    name: 'DENTAL ITEMS',
    subcategories: [
      { id: 'dental-extractors', name: 'Dental Extractors' },
      { id: 'dental-elevators', name: 'Dental Elevators' },
      { id: 'dental-probes', name: 'Dental Probes' },
      { id: 'dental-mirrors', name: 'Dental Mirrors' },
      { id: 'scalers', name: 'Scalers' },
    ],
  },
  {
    id: 'horses-riders-items',
    name: 'HORSES & RIDERS ITEMS',
    subcategories: [
      { id: 'horse-grooming', name: 'Horse Grooming' },
      { id: 'riding-equipment', name: 'Riding Equipment' },
      { id: 'horse-care', name: 'Horse Care' },
      { id: 'saddle-accessories', name: 'Saddle Accessories' },
    ],
  },
]

export const products: Product[] = [
  // ===== VETERINARY ITEMS (Matched from Saheebco) =====
  {
    id: 'A-001',
    name: 'Hoof Knife A-001',
    description: 'Professional Hoof Knife for veterinary use.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_A-001.jpg',
  },
  {
    id: 'B-002',
    name: 'Hoof Knife B-002',
    description: 'Professional Hoof Knife with wooden handle.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_B-002.jpg',
  },
  {
    id: 'D-004',
    name: 'Hoof Knife D-004',
    description: 'Left-handed Hoof Knife.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_D-004.jpg',
  },
  {
    id: 'E-005',
    name: 'Hoof Knife E-005',
    description: 'Right-handed Hoof Knife.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_E-005.jpg',
  },
  {
    id: 'G-007',
    name: 'Hoof Knife G-007',
    description: 'Loop blade Hoof Knife.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_G-007.jpg',
  },
  {
    id: 'H-008',
    name: 'Hoof Knife H-008',
    description: 'Professional Farrier Hoof Knife.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_H-008.jpg',
  },
  {
    id: 'J-009',
    name: 'Hoof Knife J-009',
    description: 'Precision Hoof Knife.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Knife',
    image: '/products-images/Hoof_Knife_J-009.jpg',
  },
  {
    id: 'A-019',
    name: 'Hoof Scraper A-019',
    description: 'Stainless Steel Hoof Scraper.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Scraper',
    image: '/products-images/Hoof_Scraper_A-019.jpg',
  },
  {
    id: 'C-021',
    name: 'Hoof Scraper C-021',
    description: 'Heavy Duty Hoof Scraper.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Scraper',
    image: '/products-images/Hoof_Scraper_C-021.jpg',
  },
  {
    id: 'B-130',
    name: 'Hoof Rasp B-130',
    description: 'Flat Hoof Rasp.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Rasp',
    image: '/products-images/Hoof_Rasp_B-130.jpg',
  },
  {
    id: 'C-031',
    name: 'Hoof Rasp C-031',
    description: 'Half-Round Hoof Rasp.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Hoof Rasp',
    image: '/products-images/Hoof_Rasp_C-031.jpg',
  },
  {
    id: 'C-173',
    name: 'Anti Kick Bar C-173',
    description: 'Stainless Steel Anti Kick Bar.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Anti Kick Bar',
    image: '/products-images/Anti_Kick_Bar_C-173.jpg',
  },
  {
    id: 'B-268',
    name: 'Bit B-268',
    description: 'Horse Bit B-268.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Bits',
    image: '/products-images/Bits_B-268.jpg',
  },
  {
    id: 'A-174',
    name: 'Bull Holder A-174',
    description: 'Bull Holder with Leader.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Bull Holders',
    image: '/products-images/Bull_Holders_A-174.jpg',
  },
  {
    id: 'A-121',
    name: 'Castration A-121',
    description: 'Burdizzo Castrator.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Castration',
    image: '/products-images/Castration_A-121.jpg',
  },
  {
    id: 'A-068',
    name: 'Dehorner A-068',
    description: 'Professional Dehorner.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Dehorner',
    image: '/products-images/Dehorner_A-068.jpg',
  },
  {
    id: 'A-060',
    name: 'Tag Applicator A-060',
    description: 'Universal Ear Tag Applicator.',
    category: 'VETERINARY ITEMS',
    subCategory: 'Tag Applicators',
    image: '/products-images/Tag_Applicators_A-060.jpg',
  },

  // ===== SURGICAL ITEMS (Coming Soon Placeholders) =====
  {
    id: 'SU-2001',
    name: 'Surgical Scissors SU-2001',
    description: 'High precision stainless steel surgical scissors.',
    category: 'SURGICAL ITEMS',
    subCategory: 'Surgical Scissors',
    image: '/images/products/surgical-scissors.png',
  },
  {
    id: 'SU-2002',
    name: 'Surgical Forceps SU-2002',
    description: 'Surgical tissue forceps with fine tips.',
    category: 'SURGICAL ITEMS',
    subCategory: 'Surgical Forceps',
    image: '/images/products/surgical-forceps.png',
  },

  // ===== DENTAL ITEMS (Coming Soon Placeholders) =====
  {
    id: 'DE-3001',
    name: 'Dental Extractor DE-3001',
    description: 'Professional dental extraction forceps.',
    category: 'DENTAL ITEMS',
    subCategory: 'Dental Extractors',
    image: '/images/products/dental-extractor.png',
  },
  {
    id: 'DE-3002',
    name: 'Dental Elevator DE-3002',
    description: 'Dental elevator for tooth luxation.',
    category: 'DENTAL ITEMS',
    subCategory: 'Dental Elevators',
    image: '/images/products/dental-elevator.png',
  },

  // ===== HORSES & RIDERS ITEMS (Coming Soon Placeholders) =====
  {
    id: 'HR-4001',
    name: 'Horse Grooming Brush HR-4001',
    description: 'Professional horse grooming brush set.',
    category: 'HORSES & RIDERS ITEMS',
    subCategory: 'Horse Grooming',
    image: '/images/products/horse-brush.png',
  },
  {
    id: 'HR-4002',
    name: 'Riding Crop HR-4002',
    description: 'Leather riding crop with wrist loop.',
    category: 'HORSES & RIDERS ITEMS',
    subCategory: 'Riding Equipment',
    image: '/images/products/riding-crop.png',
  },
]
